name: Java CI Pipeline

on:
  pull_request:
    branches: [ "master" ]

jobs:
  spotless-and-build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout 코드
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. JDK 설정 (Java 21)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set YML
        run: |
          echo ${{ secrets.APPLICATION_YML }} | base64 --decode > ./src/main/resources/application.yml

      # 3. Gradle 캐싱
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 4. Gradle 실행 권한 부여
      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x ./gradlew

      # 5. Spotless 스타일 검사
      - name: Code style check with Spotless
        run: ./gradlew spotlessCheck

      # 6. 프로젝트 빌드
      - name: Build the Project
        run: ./gradlew clean build -x test

      - name: Docker build & push to Docker repo
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          echo "docker 로그인 성공"
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/st-order .
          echo "docker 빌드 성공"
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/st-order

      - name: AWS login and docker image pull and run
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          envs: GITHUB_SHA
          script: |
            sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
            echo "docker 로그인 성공"
            sudo docker stop $(sudo docker ps -aq)
            echo "현재 실행 중인 모든 Docker 컨테이너 중지"
            sudo docker rm -f $(sudo docker ps -qa)
            echo "모든 Docker 컨테이너 강제로 삭제"
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/st-order
            echo "docker pull 성공"
            sudo docker run -d -p 80:8081 \
              -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
              ${{ secrets.DOCKERHUB_USERNAME }}/st-order
            sudo docker image prune -f
            echo "사용하지 않는 Docker image 정리"
